-- Create categories table
CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT NOT NULL
);

-- Create products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price TEXT NOT NULL,
  description TEXT DEFAULT '',
  category_id TEXT NOT NULL REFERENCES categories(id)
);

-- Insert initial categories
INSERT INTO categories (id, name, icon) VALUES
  ('cafe', 'Café', '☕'),
  ('the', 'Thé', '🍵'),
  ('boissons', 'Boissons', '🥤'),
  ('eau', 'Eau Minérale', '💧'),
  ('patisseries', 'Pâtisseries', '🥐'),
  ('salee', 'Salée', '🧂'),
  ('narguile', 'Narguilé', '🚬'),
  ('jeux', 'Jeux', '🃏')
ON CONFLICT (id) DO NOTHING;

-- Insert initial products
INSERT INTO products (name, price, description, category_id) VALUES
  ('Expresso', '1.8 DT', '', 'cafe'),
  ('Capussin', '1.9 DT', '', 'cafe'),
  ('Allongée', '1.8 DT', '', 'cafe'),
  ('Direct', '2.0 DT', '', 'cafe'),
  ('Armatora', '2.2 DT', '', 'cafe'),
  ('Filtre', '1.2 DT', '', 'cafe'),
  ('Lait Au Chocolat', 'Grand 2.0 DT / Petit 1.2 DT', '', 'cafe'),
  ('Chocolat Chaud', 'Grand 4.0 DT / Petit 3.0 DT', '', 'cafe'),
  ('Supplément SIROP', '0.2 DT', 'Vanille, Caramel et Noisette', 'cafe'),
  ('Thé Vert', '1.2 DT', '', 'the'),
  ('Thé à la Menthe', '1.5 DT', '', 'the'),
  ('Thé aux Amandes', '2.5 DT', '', 'the'),
  ('Jus Frais', '2.5 DT', 'Orange, Carotte, Citron et Fraise', 'boissons'),
  ('0,5 Litre', '1.0 DT', '', 'eau'),
  ('1 Litre', '1.4 DT', '', 'eau'),
  ('1,5 Litre', '1.6 DT', '', 'eau'),
  ('Tiramisu', '4.0 DT', 'Chocolat, Caramel', 'patisseries'),
  ('Croissant', '2.0 DT', '', 'patisseries'),
  ('Pain au Chocolat', '1.8 DT', '', 'patisseries'),
  ('MilleFeuilles', '2.0 DT', '', 'patisseries'),
  ('Pate Amondes', '1.5 DT', '', 'patisseries'),
  ('Delice', '2.0 DT', '', 'patisseries'),
  ('Gateaux', '2.0 DT', 'Chocolat, Caramel', 'patisseries'),
  ('Hrisa', '1.5 DT', '', 'patisseries'),
  ('Mini Pizza', '3.0 DT', '', 'salee'),
  ('Soufflet d''Escalope', '3.5 DT', '', 'salee'),
  ('Fricasé', '1.5 DT', '', 'salee'),
  ('Parfum Classique', '4.0 DT', 'Menthe, Raisin et Pomme', 'narguile'),
  ('Parfum Speciale', '5.0 DT', 'Love, Mi Amor, Hawaï, Melon, etc...', 'narguile'),
  ('Rami', 'Nouveau 4.0 DT / Ancien 2.0 DT', '', 'jeux'),
  ('Domino / Chkobba', 'Gratuit', '', 'jeux');
